import { AppError } from '@/lib/errors/app-error';
import { formatMoney } from '@/lib/catalog/types';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export interface PublicProduct { id: string; gameId: string; name: string; slug: string; shortDescription: string; description: string; imageUrl: string | undefined; priceMinor: number; oldPriceMinor: number | undefined; currency: string; formattedPrice: string; formattedOldPrice: string | undefined }
type ProductRow = { id:string; game_id:string; name:string; slug:string; short_description:string|null; description:unknown; image_media_id:string|null; price_minor:number|string; old_price_minor:number|string|null; currency:string };
const content = (value: unknown) => typeof value === 'object' && value !== null && 'content' in value && typeof (value as {content?:unknown}).content === 'string' ? (value as {content:string}).content : '';
async function mapProducts(rows: ProductRow[]): Promise<PublicProduct[]> {
  const supabase = createServerSupabaseClient(); const ids = [...new Set(rows.map((row) => row.image_media_id).filter((id): id is string => Boolean(id)))]; const media = new Map<string,string>();
  if (ids.length) { const { data, error } = await supabase.from('media_assets').select('id,storage_bucket,storage_path').in('id', ids).is('deleted_at', null); if (error) throw new AppError('INTERNAL_ERROR','Unable to load product media',{code:error.code}); for (const asset of data ?? []) media.set(asset.id, supabase.storage.from(asset.storage_bucket).getPublicUrl(asset.storage_path).data.publicUrl); }
  return rows.map((row) => { const price = Number(row.price_minor); const old = row.old_price_minor == null ? undefined : Number(row.old_price_minor); if (!Number.isSafeInteger(price) || (old !== undefined && !Number.isSafeInteger(old))) throw new AppError('INTERNAL_ERROR','Invalid product price'); return { id:row.id, gameId:row.game_id, name:row.name, slug:row.slug, shortDescription:row.short_description ?? '', description:content(row.description), imageUrl:row.image_media_id ? media.get(row.image_media_id) : undefined, priceMinor:price, oldPriceMinor:old, currency:row.currency, formattedPrice:formatMoney(price,row.currency), formattedOldPrice:old === undefined ? undefined : formatMoney(old,row.currency) }; });
}
export async function listPublicProducts(options: { gameId?: string | undefined; ids?: string[] | undefined } = {}): Promise<PublicProduct[]> { let query = createServerSupabaseClient().from('products').select('id,game_id,name,slug,short_description,description,image_media_id,price_minor,old_price_minor,currency').order('sort_order').order('name'); if (options.gameId) query = query.eq('game_id',options.gameId); if (options.ids?.length) query = query.in('id',options.ids); const {data,error}=await query; if(error) throw new AppError('INTERNAL_ERROR','Unable to load products',{code:error.code}); return mapProducts((data ?? []) as ProductRow[]); }
export async function getPublicProduct(slug:string):Promise<PublicProduct|null>{ const {data,error}=await createServerSupabaseClient().from('products').select('id,game_id,name,slug,short_description,description,image_media_id,price_minor,old_price_minor,currency').eq('slug',slug).maybeSingle(); if(error) throw new AppError('INTERNAL_ERROR','Unable to load product',{code:error.code}); if(!data)return null; return (await mapProducts([data as ProductRow]))[0] ?? null; }
